apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ckerwfkmd-go 
  janus-idp.io/tekton: ckerwfkmd-go
  backstage.io/kubernetes-id: ckerwfkmd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ckerwfkmd-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml